CREATE TABLE [Character]
(
	[Id]			UNIQUEIDENTIFIER PRIMARY KEY,
	[MarvelId]		INT NOT NULL,
	[Name]			VARCHAR(200) NOT NULL,
	[Thumbnail]		VARCHAR(200),
	[Description]	VARCHAR(1000),
	[Modified]		DATETIME
)

CREATE TABLE [Comic]
(
	[Id]			UNIQUEIDENTIFIER PRIMARY KEY,
	[Name]			VARCHAR(200) NOT NULL
)

CREATE TABLE [CharacterComics]
(
	[Id]			UNIQUEIDENTIFIER PRIMARY KEY,
	[CharacterId]	UNIQUEIDENTIFIER NOT NULL,
	[ComicId]		UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_CHARACTERCOMICS_CHARACTER FOREIGN KEY([CharacterId]) REFERENCES [Character]([Id]),
    CONSTRAINT FK_CHARACTERCOMICS_COMIC     FOREIGN KEY([ComicId]) REFERENCES [Comic]([Id])
)

CREATE TABLE [Serie]
(
	[Id]			UNIQUEIDENTIFIER PRIMARY KEY,
	[Name]			VARCHAR(200) NOT NULL
)

CREATE TABLE [CharacterSeries]
(
	[Id]			UNIQUEIDENTIFIER PRIMARY KEY,
	[CharacterId]	UNIQUEIDENTIFIER NOT NULL,
	[SerieId]		UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_CHARACTERSERIES_CHARACTER FOREIGN KEY([CharacterId]) REFERENCES [Character]([Id]),
    CONSTRAINT FK_CHARACTERSERIES_SERIE     FOREIGN KEY([SerieId]) REFERENCES [Serie]([Id])
)

CREATE TABLE [Event]
(
	[Id]			UNIQUEIDENTIFIER PRIMARY KEY,
	[Name]			VARCHAR(200) NOT NULL
)

CREATE TABLE [CharacterEvents]
(
	[Id]			UNIQUEIDENTIFIER PRIMARY KEY,
	[CharacterId]	UNIQUEIDENTIFIER NOT NULL,
	[EventId]		UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_CHARACTEREVENTS_CHARACTER FOREIGN KEY([CharacterId]) REFERENCES [Character]([Id]),
    CONSTRAINT FK_CHARACTEREVENTS_EVENT     FOREIGN KEY([EventId]) REFERENCES [Event]([Id])
)